# Generated by Django 3.0.5 on 2020-06-08 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('endtime', models.DateTimeField(blank=True, null=True)),
                ('link', models.URLField(blank=True, max_length=300)),
                ('completed', models.BooleanField(blank=True, default=False)),
                ('series', models.CharField(blank=True, max_length=100)),
                ('episode', models.IntegerField(blank=True, null=True)),
                ('richtext', models.TextField(blank=True)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to='')),
                ('name', models.CharField(max_length=300)),
                ('thumbnail', models.ImageField(upload_to='')),
                ('category', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
