# Generated by Django 3.0.5 on 2020-06-10 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='stoptime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t1', models.DateTimeField(blank=True, null=True)),
                ('t2', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='books',
            name='dateadded',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='articles',
            name='stops',
            field=models.ManyToManyField(blank=True, null=True, to='main.stoptime'),
        ),
    ]
